export default {
  SPREMI_KATEGORIJE: 'SPREMI_KATEGORIJE',
  SPREMI_VIC: 'SPREMI_VIC',
  IZBRISI_VIC: 'IZBRISI_VIC',
  IZABERI_KATEGORIJU: 'IZABERI_KATEGORIJU',
  IZBRISI_SVE_VICEVE: 'IZBRISI_SVE_VICEVE',
};
